language: php

php:
  - '7.2'
  - '7.3'

env:
  - PHPUNIT_VERSION=""
  - PHPUNIT_VERSION="~8.2.0"
  - PHPUNIT_VERSION="~8.1.0"
  - PHPUNIT_VERSION="~8.0.0"
  - PHPUNIT_VERSION="~7.0"
  - PHPUNIT_VERSION="~6.0"
  - PHPUNIT_VERSION="~5.0"

matrix:
  include:
    - php: '7.1'
      env: PHPUNIT_VERSION="~5.0"
    - php: '7.1'
      env: PHPUNIT_VERSION="~6.0"
    - php: '7.1'
      env: PHPUNIT_VERSION="~7.0"

before_install:
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require --dev --no-update phpunit/phpunit:$PHPUNIT_VERSION; fi

install:
  - travis_retry composer install --no-progress --prefer-dist

script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit --bootstrap $TRAVIS_BUILD_DIR/vendor/autoload.php $TRAVIS_BUILD_DIR/tests/
